"use client"

import { useEffect, useState } from "react"

interface Report {
  id: string
  report_type: string
  report_period_start: string
  report_period_end: string
  generated_at: string
  generated_by: string | null
  report_data: Record<string, unknown>
}

export default function ReportsPage() {
  const [reports, setReports] = useState<Report[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    fetch(`${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000"}/reports`)
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`)
        return res.json()
      })
      .then((data) => {
        setReports(data.reports || [])
        setLoading(false)
      })
      .catch((err) => {
        console.error("Failed to fetch reports:", err)
        setError(err.message)
        setLoading(false)
      })
  }, [])

  if (loading) {
    return <div className="p-8 text-gray-700">Loading...</div>
  }

  return (
    <div className="p-8">
      <h1 className="text-3xl font-bold mb-6">M2 Reports</h1>

      {error && (
        <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded text-red-700 text-sm">
          Error: {error}
          <button onClick={() => setError(null)} className="ml-2 underline">Close</button>
        </div>
      )}

      <div className="bg-white rounded-lg shadow">
        {reports.length === 0 ? (
          <p className="p-6 text-gray-500">No reports generated yet.</p>
        ) : (
          <div className="divide-y divide-gray-200">
            {reports.map((report) => (
              <div key={report.id} className="p-6 border-b last:border-b-0">
                <div className="flex items-start justify-between mb-4">
                  <div>
                    <h2 className="text-lg font-semibold text-gray-900">{report.report_type}</h2>
                    <p className="text-xs text-gray-500 mt-1">ID: {report.id}</p>
                  </div>
                  <span className="px-3 py-1 bg-blue-100 text-blue-800 text-xs font-medium rounded">
                    {new Date(report.generated_at).toLocaleDateString()}
                  </span>
                </div>

                <div className="grid grid-cols-2 gap-4 mb-4">
                  <div>
                    <span className="text-xs text-gray-500 uppercase">Period Start</span>
                    <p className="text-gray-900 text-sm mt-1">
                      {new Date(report.report_period_start).toLocaleString()}
                    </p>
                  </div>
                  <div>
                    <span className="text-xs text-gray-500 uppercase">Period End</span>
                    <p className="text-gray-900 text-sm mt-1">
                      {new Date(report.report_period_end).toLocaleString()}
                    </p>
                  </div>
                </div>

                {report.generated_by && (
                  <div className="mb-4">
                    <span className="text-xs text-gray-500 uppercase">Generated By</span>
                    <p className="text-gray-700 text-sm mt-1">{report.generated_by}</p>
                  </div>
                )}

                {report.report_data && (
                  <div className="mt-4 p-3 bg-gray-50 rounded text-xs">
                    <pre className="overflow-x-auto text-gray-700">
                      {JSON.stringify(report.report_data, null, 2)}
                    </pre>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}
